name: Release Packages

on:
  push:
    tags:
      - 'v*'  # Фильтр для тегов, начинающихся с 'v'

jobs:
  build-packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package_type: [deb, rpm]  # Добавьте другие типы пакетов при необходимости
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Обновлено до v4
      with:
        fetch-depth: 0
        
    - name: Set up JDK 17
      uses: actions/setup-java@v4  # Обновлено до v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: Build and create packages
      run: |
        ./gradlew build
        ./gradlew create${matrix.package_type}
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4  # КРИТИЧЕСКОЕ ИСПРАВЛЕНИЕ: v3 → v4
      with:
        name: ${{ matrix.package_type }}-package
        path: build/distributions/*.${{ matrix.package_type }}
        
  create-release:
    needs: build-packages
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4  # Обновлено до v4
      with:
        path: artifacts
        
    - name: Create Release
      uses: softprops/action-gh-release@v2  # Обновлено до v2
      with:
        tag_name: ${{ github.ref_name }}
        name: "Release ${{ github.ref_name }}"
        files: artifacts/**/*
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
